server:
  port: 8080

spring:
  application:
    name: Capitals-Cloud-Authorization
  boot:
    admin:
      client:
        url: http://jiangxicheng.online:17001
        enabled: true
  cloud:
    zookeeper:
      connect-string: jiangxicheng.online:2181
  datasource:
    url: jdbc:postgresql://jiangxicheng.online:15432/capitals
    username: capitals
    password: capitals
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"