spring:
  boot:
    admin:
      client:
        url: http://jiangxicheng.online:17001
        enabled: true
  cloud:
    zookeeper:
      connect-string: jiangxicheng.online:2181
      discovery:
        root: /services/${spring.profiles.active}/
  rabbitmq:
    host: jiangxicheng.online
    port: 5672
    username: rabbitmq
    password: rabbitmq
  session:
    redis:
      repository-type: indexed
      namespace: "spring:session"
      flush-mode: immediate
      save-mode: always
    timeout: 30m
  data:
    redis:
      host: jiangxicheng.online
      port: 6379
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://jiangxicheng.online:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  config: https://raw.githubusercontent.com/jxch-capital/capitals/refs/heads/main/capitals-config-center/logback-spring.xml
