spring:
  boot:
    admin:
      client:
        url: jiangxicheng.online/inner/admin
        enabled: true
  cloud:
    zookeeper:
      connect-string: jiangxicheng.online:2181
      discovery:
        root: /services/${spring.profiles.active}/
  rabbitmq:
    host: jiangxicheng.online
    port: 5672
    username: rabbitmq
    password: rabbitmq

management:
  endpoints:
    web:
      exposure:
        include: "*"
