spring:
  application:
    name: Capitals-Cloud-Admin
  boot:
    admin:
      discovery:
        enabled: true
      ui:
        title: "Capitals Cloud Admin"
      client:
        url: http://jiangxicheng.online:17001
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"