services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - cloud_bus
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
    networks:
      - cloud_bus
  caddy:
    image: caddy:2
    environment:
      - CADDY_API=http://127.0.0.1:2019
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
    configs:
      - source: caddyfile

configs:
  caddyfile:
    file: /root/cloud/config/caddy2/Caddyfile

volumes:
  mysql_data:
    driver_opts:
      type: "nfs"
      o: "addr=amd2.jiangxicheng.online,rw"
      device: ":/srv/nfs/mysql_data"
  redis_data:
    driver_opts:
      type: "nfs"
      o: "addr=amd2.jiangxicheng.online,rw"
      device: ":/srv/nfs/redis_data"
  zookeeper_data:
    driver_opts:
      type: "nfs"
      o: "addr=amd2.jiangxicheng.online,rw"
      device: ":/srv/nfs/zookeeper_data"
  caddy_data:
    driver_opts:
      type: "nfs"
      o: "addr=amd2.jiangxicheng.online,rw"
      device: ":/srv/nfs/caddy_data"


networks:
  cloud_bus:
    external: true
