spring:
  application:
    name: Capitals-Cloud-Gateway
  security:
    permits: /public/**,/inner/**,/actuator/**
  cloud:
    sentinel:
#      datasource:
#        zookeeper:
#          zk:
#            server-addr: jiangxicheng.online:2181
#            group-id: capitals
#            path: sentinel
#            data-id: gateway
#            rule-type: flow
#            data-type: json
      transport:
        dashboard: jiangxicheng.online:8088
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: capitals-config-center-route
          uri: lb://Capitals-Cloud-Config
          predicates:
            - Path=/inner/config-center/**
          filters:
            - StripPrefix=2
        - id: capitals-chart-route
          uri: lb://Capitals-Chart
          predicates:
            - Path=/public/chart/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowed-methods:
              - "*"
            allowed-headers:
              - "*"
            exposed-headers:
              - "Set-Cookie"
              - "Authorization"
            allow-credentials: true

logging:
  level:
    root: info
    com.alibaba.cloud.sentinel.endpoint.SentinelHealthIndicator: warn
    io.netty.resolver.dns: INFO
