spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: capitals
            client-secret: ObgtuH7bWX4fdI7hY5QI6BRqX7aMOVkw
            scope: openid
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: /capitals/
        provider:
          keycloak:
            issuer-uri: http://jiangxicheng.online:8081/realms/Capitals
      resourceserver:
        jwt:
          jwk-set-uri: http://jiangxicheng.online:8081/realms/Capitals/protocol/openid-connect/certs
