server:
  port: 8080

spring:
  application:
    name: Capitals-Cloud-Admin
  boot:
    admin:
      discovery:
        enabled: true
      ui:
        title: "Capitals Cloud Admin"
      client:
        url: http://jiangxicheng.online:17001
        enabled: true
  cloud:
    zookeeper:
      connect-string: jiangxicheng.online:2181
    config:
      server:
        git:
          uri: https://github.com/jxch-capital/capitals
          searchPaths:
            - 'capitals-config-center'
          cloneOnStart: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
