server:
  port: 8080

spring:
  application:
    name: Capitals-Cloud-Admin
  boot:
    admin:
      discovery:
        enabled: true
      ui:
        title: "Capitals Cloud Admin"
  cloud:
    zookeeper:
      connect-string: jiangxicheng.online:2181
